### ISSUE TITLE
Build a dashboard page to include stats about a particular run

### ISSUE THREAD

**Issue by 0xedward** [MLH-Fellowship/sapp#10]
The idea is to create a stats page where we display aggregate metrics for the particular Run the user has selected. An example uri for this could be `localhost.com/run/1/stats`

The starting list of metrics include:
- How many issues were found by warning code (e.g. 8 issues were 6073) 
- Number of issues by status (e.g. 10 issues were marked as `Valid`)
- % of issues that were triaged (e.g. all issues not marked as Uncategorized / total number of issues)
- Number of issues by filter name and status (e.g.  if the user applied `High signal SQL injection` they would've seen 10 issues. 5 of which were `Valid`, 2 of which were `Uncategorized`, etc )

Additional list of metrics we would love to have. We may decide to make this a separate page called "Insights":
- List of common callables in traces shared among all issues
- List of common callables in traces shared among `False Positive` and `Do Not Care` issues
- List of common features among invalid issues
- Files containing most of the issues

If you're interested in this project, let's chat about other metrics you would like to include and how we want to display the information to the user (e.g. tables, charts, etc) :)

**Comment by abishekvashok** [comment]
I would love to take this up :)

**Comment by abishekvashok** [comment]
Closed via https://github.com/facebook/sapp/commit/1fc57ccca6347095147a747d073c09633e6c8a4a
