### ISSUE TITLE
Web UI does not display the last character of callable's class name for MT issues

### ISSUE THREAD

**Issue by 0xedward** [MLH-Fellowship/sapp#3]
## Description:
![image](https://user-images.githubusercontent.com/14011954/134803966-8e9d6b65-acab-4f1d-976a-a879e0075faa.png)

In the screenshot above, notice that for the Callable field, `MainActivit` is missing a `y`. This issue reproduces for all MT issues. Note that this may not be the only location the Callable field appears. For example, in each trace frame the Callable is displayed at the top:
![image](https://user-images.githubusercontent.com/14011954/134806991-5994f3bf-dcaf-43b5-bd7b-61f764908c4f.png)

## Steps to Reproduce:
Here's a [zip of a SAPP db](https://github.com/MLH-Fellowship/sapp/files/7231200/sapp.db.zip) containing the MT run to help you reproduce the issue, extract it and run the following command to get started looking into this in SAPP:
```
python3 -m sapp.cli --database-name sapp.db --debug
```

As a code pointer to get you started on fixing this issue, the root cause of the issue appears to be here: https://github.com/facebook/sapp/blob/main/sapp/ui/frontend/src/HumanReadable.js#L76

**Comment by abishekvashok** [comment]
Closed via https://github.com/facebook/sapp/commit/d74193c72b6d27b8c3af8a06052fb9e08cb37302
