### ISSUE TITLE
Add proper syntax highlighting support for Java in Web UI for MT issues

### ISSUE THREAD

**Issue by 0xedward** [MLH-Fellowship/sapp#5]
## Steps to Reproduce:
1. Download the [zip of a SAPP db](https://github.com/MLH-Fellowship/sapp/files/7231200/sapp.db.zip) containing the MT run to help you reproduce the issue and the [source code of what MT was run on](https://github.com/MLH-Fellowship/sapp/files/7231267/repo.zip)

2. Extract both zip files and run the following command to get started looking into this in SAPP
```
python3 -m sapp.cli --database-name sapp.db --source-directory repo/ --debug
```
3. Visit http://localhost:3000 and click on Issue `1` in Run `1`
![image](https://user-images.githubusercontent.com/14011954/134806843-3768af8d-a8a7-497b-a108-72e254031daf.png)
4. Notice that reserved words (e.g. `public`) and return types (e.g. `void`) aren't highlighted, while other syntax that doesn't seem important in Java (e.g. `from:` in the comment line) is highlighted
![image](https://user-images.githubusercontent.com/14011954/134806858-c8676242-d7dd-4046-b7ee-a444634affa4.png)

## Expected result:
For each trace frame for MT issues, the code displayed has Java reserved words highlighted and no irrelevant syntax highlighted

**Comment by abishekvashok** [comment]
Fixed via https://github.com/facebook/sapp/pull/47

**Comment by abishekvashok** [comment]
closed via https://github.com/facebook/sapp/commit/b1c6f980c8f27c2f0e2d3bb04d82c088dfad371a
