### ISSUE TITLE
Update tooltip for Sources and Sinks in Web UI to display information specific to each `Source` and `Sink`

### ISSUE THREAD

**Issue by 0xedward** [MLH-Fellowship/sapp#6]
## Description:
We want to copy the behavior we have currently with Callables for Sources and Sinks.

![image](https://user-images.githubusercontent.com/14011954/134807318-8c231b2f-4ff6-4d93-ac50-62f5b8e1c8e3.png)

Currently for Sources and Sinks, when we hover over the element, it displays a tooltip containing `Explanation for kind`.

![image](https://user-images.githubusercontent.com/14011954/134807394-36f1c263-6441-42e2-be67-2406260ceb27.png)

Instead we want to replace the tooltip content with a description of the Source or Sink. To do this, you might need to update the following line in [`Leaves` in `Issue.js`](https://github.com/facebook/sapp/blob/7be0ee6fe94b2f11d6a73b923ccd31ec8100e07f/sapp/ui/frontend/src/Issue.js#L106). However, it might be possible that SAPP currently does not store descriptions for Sources and Sinks in a table. In that case, we can discuss next steps from there.

## Steps to Reproduce:
_Note you don't need to use the provided files if you have an existing SAPP db you would like to use instead. The tooltip for Sources and Sinks are the same for Pysa and MT runs._
1. Download the [zip of a SAPP db](https://github.com/MLH-Fellowship/sapp/files/7231200/sapp.db.zip) containing the MT run to help you reproduce the issue and the [source code of what MT was run on](https://github.com/MLH-Fellowship/sapp/files/7231267/repo.zip)

2. Extract both zip files and run the following command to get started looking into this in SAPP
```
python3 -m sapp.cli --database-name sapp.db --source-directory repo/ --debug
```

## Submitting a PR

We use the following linters internally, so to save everyone's time, please make sure you run the following linters locally and fix errors related to the files you modified before submitting a PR:
```
black && usort format . && flake8
```

To install the linters, you can run the following command:
```
pip install flake8 usort black==21.4b2
```

**Comment by abishekvashok** [comment]
Quick question. From what I see in the db:

<img width="1440" alt="Screenshot 2021-10-04 at 7 52 55 PM" src="https://user-images.githubusercontent.com/8947010/135868633-bf435217-25de-4c15-8a34-441afbbe64a1.png">

`source_details` and `sink_details` contain things similar to callables (I assume this is the Dalvik representation). But those are displayed "as-is". Is this issue in anyway to display this entire source/sink detail on popup and show a "HumanReadable Version" of the  "Dalvik Representation" as we do for callables?

**Comment by abishekvashok** [comment]
Assuming this is true, I made the above PR :)

**Comment by 0xedward** [comment]
> Is this issue in anyway to display this entire source/sink detail on popup and show a "HumanReadable Version" of the "Dalvik Representation" as we do for callables?

@abishekvashok I think we want to display the description of the SourceKind or SinkKind in the tooltip. For example, `CodeExecution` would display something like `Executes shell command` (cc @dkgi to make sure that is what the original feature request was)

> However, it might be possible that SAPP currently does not store descriptions for Sources and Sinks in a table. In that case, we can discuss next steps from there.

We might need to discuss what to do here if my understanding of the feature request is correct
