### ISSUE TITLE
Add similar flows on issues

### ISSUE THREAD

**Issue by 0xedward** [MLH-Fellowship/sapp#9]
While triaging issues, it's often helpful to see other source to sink traces that are similar. The goal of this project is to do the following:

1. Create a method for determining similarity between traces (e.g. similarity score)
2. With the existing schema, implement a way to calculate that score
3. Create a view to display similar traces (e.g. sidebar on each issue linking to similar other issues)

Ideas for signals to use while calculating similarity score:
- Does the source callable and sink callable name match?
- How many of the source kinds and sink kinds match?
- Does the source to sink trace between two issues pass through the same files? 

We can spawn a separate issue for this when ready - follow up idea to this project is to find and update all duplicate issues when a user changes the status of one issue

## Submitting a PR

We use the following linters internally, so to save everyone's time, please make sure you run the following linters locally and fix errors related to the files you modified before submitting a PR:
```
black && usort format . && flake8
```

To install the linters, you can run the following command:
```
pip install flake8 usort black==21.4b2
```

**Comment by abishekvashok** [comment]
Fixed via https://github.com/facebook/sapp/commit/02a7eb6da4641ba9c1cba912b3b9114073f83920
